# **Data 1 dimension**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd


In [5]:
irish_1d =  pd.read_csv('iris_1D.csv')
#get x
irish_x= irish_1d['Petal_Length'].to_numpy()
irish_x=irish_x.reshape(6,1)
irish_x

array([[1.4],
       [1. ],
       [1.5],
       [3.1],
       [3.8],
       [4.1]])

In [6]:
# get y
irish_y = irish_1d['Label'].to_numpy()
irish_y

array([0., 0., 0., 1., 1., 1.])

In [7]:
#give x test, define y test
x_test = [[6.4]]

In [8]:
# get model With K is odd
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(irish_x, irish_y)

KNeighborsClassifier(n_neighbors=3)

In [9]:
y_pred = classifier.predict(x_test)
print(y_pred)

[1.]


In [10]:
# get model With K is even
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(irish_x, irish_y)
y_pred = classifier.kneighbors(x_test)
print(y_pred)



(array([[2.3, 2.6, 3.3, 4.9, 5. , 5.4]]), array([[5, 4, 3, 2, 0, 1]]))


In [11]:
classifier.classes_[classifier._y[3]] #tại sao y[3]

1.0

# Data with 2 dimension

In [9]:
irish_2d = pd.read_csv('/kaggle/input/knn-aio/iris_2D.csv')
irish_2d


Petal_Length  Petal_Width  Label
0           1.4          0.2    0.0
1           1.3          0.4    0.0
2           1.4          0.3    0.0
3           4.0          1.0    1.0
4           4.7          1.4    1.0
5           3.6          1.3    1.0

In [10]:
# get x feature
irish_2d_x = irish_2d[['Petal_Length', 'Petal_Width']].to_numpy()
irish_2d_x = irish_2d_x.reshape(6, 2)
print(irish_2d_x)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]


In [11]:
# give x unknown
x_2d_test = [[2.6,0.7]]

In [12]:
# get y
irish_2d_y = irish_2d['Label'].to_numpy()
irish_2d_y

array([0., 0., 0., 1., 1., 1.])

In [13]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(irish_2d_x, irish_2d_y)

KNeighborsClassifier(n_neighbors=6)

In [14]:
y_pred = classifier.predict(x_2d_test)
print(y_pred)

[0.]


In [15]:
# test code, no relevant KNN
import numpy as np
import torch
import tensorflow as tf
a = np.array([1,2,3])
b = torch.tensor([4,5,6])
c = tf.constant([7,8,9])

r = c - (b@a)*a
print(r)
d=b@a
print(d)

2024-03-06 02:07:35.186382: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-06 02:07:35.186497: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-06 02:07:35.330829: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


tf.Tensor([-25 -56 -87], shape=(3,), dtype=int32)
tensor(32)
